baseURL: "https://torwald-sergesson.github.io/"
languageCode: "en-us"
title: "Torwald Log"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/notes/:slug/"
  post: "/posts/:year/:month/:day/:slug/"

params:
  description: "Torwald Sergesson log"
  footer: "&copy; Torwald Sergesson 2021"

# Main menu which appears below site header.
menu:
  main:
  - name: "Home"
    url: "/"
    weight: 1
  - name: "About"
    url: "/about"
    weight: 2
  - name: "Posts"
    url: "/posts"
    weight: 3
  - name: "Notes"
    url: "/notes"
    weight: 4
  - name: "Tags"
    url: "/tags"
    weight: 6
  - name: "Categories"
    url: "categories/"
    weight: 5

