baseURL: "https://torwald-sergesson.github.io/"
languageCode: "en-us"
title: "Torwald Log"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/pages/:slug/"
  post: "/blog/:year/:month/:day/:slug/"

params:
  description: "Torwald Sergesson log"
  footer: "&copy; Torwald Sergesson 2021-2024"

markup:
  goldmark:
    renderer:
      unsafe: true

# Main menu which appears below site header.
menu:
  main:
  - name: "Home"
    url: "/"
    weight: 1
  - name: "Blog"
    url: "/blog"
    weight: 3
  - name: "Dev"
    url: "/dev"
    weight: 4
  - name: "Games"
    url: "/games"
    weight: 5
  - name: "Fitness"
    url: "/fitness"
    weight: 4
  - name: "Tags"
    url: "/tags"
    weight: 9
  - name: "Categories"
    url: "categories/"
    weight: 8
  - name: "About me"
    url: "/about"
    weight: 10

